name: Run Discord Request Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U discord.py gspread google-auth

      - name: Run bot
        env:
          # ========= Discord =========
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

          # ========= Google =========
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

          # ========= チャンネルID =========
          LOWER_REQUEST_CHANNEL_ID: "1469311152671428680"
          UPPER_REQUEST_CHANNEL_ID: "1469310757018665012"
          LOWER_UPPER_LIST_CHANNEL_ID: "1469310840837640242"

          INCOLLE_REQUEST_CHANNEL_ID: "1469310789209817301"
          INCOLLE_LIST_CHANNEL_ID: "1469310877340668139"

          # ========= 下中級生/上級生 =========
          LU_SPREADSHEET_ID: ${{ secrets.LU_SPREADSHEET_ID }}
          LU_SHEET_NAME: "チャレンジ指導回答"
          LU_TS_COLUMN_INDEX: "1"
          LU_NAME_COL_INDEX: "28"
          LU_STATUS_COL_INDEX: "29"

          LU_MENTION_SPREADSHEET_ID: ${{ secrets.LU_MENTION_SPREADSHEET_ID }}
          LU_MENTION_SHEET_NAME: "メンション"

          # ========= インカレ =========
          INC_SPREADSHEET_ID: ${{ secrets.INC_SPREADSHEET_ID }}
          INC_SHEET_NAME: "チャレンジ指導回答"
          INC_TS_COLUMN_INDEX: "1"
          INC_NAME_COL_INDEX: "27"
          INC_STATUS_COL_INDEX: "28"

          INC_MENTION_SPREADSHEET_ID: ${{ secrets.INC_MENTION_SPREADSHEET_ID }}
          INC_MENTION_SHEET_NAME: "メンション"

        run: |
          python bot.py
